###
GET http://localhost:8080/

###
GET http://localhost:8080/swagger-ui.html

###
GET http://localhost:8080/v2/api-docs

###
POST http://localhost:8080/schedule/generate HTTP/1.1 
content-type: application/json

{ "name":"first-schedule","startDate":"2018-09-10", "noOfWorkingDays":10, "noOfEmployees":10, "offDaysOfWeek":["SUNDAY","SATURDAY"],"minRestShift":4, "noOfShiftsPerEmployee":2 }

